// ── Rank System — Level-based titles with colors & effects ───────────────────

export const RANKS = [
  {
    min: 0, max: 49,
    name: "Pemula",
    emoji: "🌱",
    color: "text-slate-400",
    bg: "bg-slate-500/15",
    border: "border-slate-500/30",
    gradient: "from-slate-500 to-slate-400",
    textColor: "#94a3b8",
    animated: false,
  },
  {
    min: 50, max: 149,
    name: "Prajurit",
    emoji: "⚔️",
    color: "text-blue-400",
    bg: "bg-blue-500/15",
    border: "border-blue-500/30",
    gradient: "from-blue-600 to-blue-400",
    textColor: "#60a5fa",
    animated: false,
  },
  {
    min: 150, max: 499,
    name: "Kesatria",
    emoji: "🛡️",
    color: "text-emerald-400",
    bg: "bg-emerald-500/15",
    border: "border-emerald-500/30",
    gradient: "from-emerald-600 to-teal-400",
    textColor: "#34d399",
    animated: false,
  },
  {
    min: 500, max: 2499,
    name: "Pendekar",
    emoji: "🔥",
    color: "text-orange-400",
    bg: "bg-orange-500/15",
    border: "border-orange-500/30",
    gradient: "from-orange-600 to-yellow-400",
    textColor: "#fb923c",
    animated: false,
  },
  {
    min: 2500, max: 9999,
    name: "Legenda",
    emoji: "⚡",
    color: "text-purple-400",
    bg: "bg-purple-500/20",
    border: "border-purple-500/40",
    gradient: "from-purple-600 to-pink-500",
    textColor: "#c084fc",
    animated: true,
    animStyle: "purple-glow",
  },
  {
    min: 10000, max: 49999,
    name: "Mitos",
    emoji: "🌌",
    color: "text-sky-300",
    bg: "bg-sky-500/20",
    border: "border-sky-400/50",
    gradient: "from-cyan-500 to-blue-400",
    textColor: "#7dd3fc",
    animated: true,
    animStyle: "cyan-glow",
  },
  {
    min: 50000, max: 199999,
    name: "Abadi",
    emoji: "👑",
    color: "text-yellow-300",
    bg: "bg-yellow-500/20",
    border: "border-yellow-400/50",
    gradient: "from-yellow-400 to-amber-300",
    textColor: "#fde047",
    animated: true,
    animStyle: "gold-glow",
  },
  {
    min: 200000, max: Infinity,
    name: "Dewa Anime",
    emoji: "🌟",
    color: "text-white",
    bg: "bg-gradient-to-r from-pink-500/20 via-purple-500/20 to-blue-500/20",
    border: "border-pink-400/60",
    gradient: "from-pink-500 via-purple-500 to-blue-500",
    textColor: "#ffffff",
    animated: true,
    animStyle: "rainbow",
  },
];

export function getRankByLevel(level) {
  return RANKS.find((r) => level >= r.min && level <= r.max) || RANKS[0];
}